### ISSUE TITLE
Actividad 5 cuadro comparativo

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Diegocruz040708#1]
Actividad 5
Diego Cruz Cruz
[Actividad 5 Cuadro comparativo Diego CC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Diegocruz040708/files/9641422/Actividad.5.Cuadro.comparativo.Diego.CC.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 5
Obtuviste un 18% de los 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
